import { chromium } from 'playwright';
const BASE='http://127.0.0.1:8080';
const b=await chromium.launch({executablePath:'/opt/pw-browsers/chromium'});
const ctx=await b.newContext({viewport:{width:1400,height:900},deviceScaleFactor:2});
const p=await ctx.newPage();
await p.goto(BASE,{waitUntil:'networkidle'}); await p.waitForTimeout(2500);
await p.screenshot({path:'/tmp/demo/claro-home.png'});
await p.evaluate(()=>window.scrollTo(0,1450)); await p.waitForTimeout(1200);
await p.screenshot({path:'/tmp/demo/claro-produtos.png'});
await p.evaluate(()=>window.scrollTo(0,document.body.scrollHeight-950)); await p.waitForTimeout(1500);
await p.screenshot({path:'/tmp/demo/claro-rodape.png'});
await p.goto(BASE+'/admin',{waitUntil:'networkidle'});
await p.fill('#admin-email','admin@queopspiramides.com.br');
await p.fill('#admin-pass','DemoQueops2026!');
await p.click('button[type=submit]'); await p.waitForTimeout(3000);
await p.screenshot({path:'/tmp/demo/claro-painel.png'});
await b.close(); console.log('claro ok');
