/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 *
 * SEMENTE do catálogo — não é mais lida pela loja em tempo de execução.
 *
 * A vitrine e o painel consomem o banco (`GET /api/catalog`). Este arquivo
 * alimenta a carga inicial: `node scripts/export-catalog.mjs` transforma estes
 * arrays em `api/seed/catalog.json`, que o `php api/migrate.php` importa.
 *
 * Dados coletados do site oficial (queopspiramides.com.br) via API pública do
 * WooCommerce. Depois da carga, edite os produtos pelo painel, não aqui.
 */

import { Product, Category, ValueProp, MenuCategory } from './types';

export const CATEGORIES: Category[] = [
  { id: 'all', name: 'Início', description: 'Catálogo completo' },
  { id: 'piramides', name: 'Pirâmides', description: 'Pirâmides de Cobre, Pirâmides de Cristal, Pirâmides de Veludo Azul, Pirâmides de' },
  { id: 'cristais', name: 'Cristais', description: 'Cristais, Materia Prima' },
  { id: 'incensos', name: 'Incensos', description: 'Incensos, Incensários, Essências, Difusores' },
  { id: 'acessorios', name: 'Acessórios', description: 'Pingentes e Brincos, Pulseiras, Peças em Prata, Chaveiros, Porta Crachás' },
  { id: 'radiestesia', name: 'Radiestesia', description: 'Pêndulos, Radiestesia, Bússolas' },
  { id: 'religiosos', name: 'Religiosos', description: 'São Francisco, Joana d\'Arc, Cristo, Cruzes, Egípcios, Indianos' },
  { id: 'decoracao', name: 'Decoração', description: 'Estátuas e Enfeites, Quadros, Fotos e Porta Retratos, Velas e Porta Velas, Papir' },
  { id: 'livros-e-midia', name: 'Livros e Mídia', description: 'Livros, Infantil, Filmes DvD\'s' },
];

// Mega-menu — categorias-mãe com subcategorias reais do catálogo Quéops
export const MENU_CATEGORIES: MenuCategory[] = [
  { id: 'destaques', name: 'Destaques', icon: 'Star', featured: true, subcategories: [] },
  {
    id: 'piramides',
    name: 'Pirâmides',
    icon: 'Triangle',
    subcategories: [
      { id: 'piramides-de-cobre', name: 'Pirâmides de Cobre' },
      { id: 'piramides-de-cristal', name: 'Pirâmides de Cristal' },
      { id: 'piramides-de-veludo-azul', name: 'Pirâmides de Veludo Azul' },
      { id: 'piramides-de-ametista-e-outros', name: 'Pirâmides de Ametista e Outros' },
      { id: 'piramides-de-impressao-3d', name: 'Pirâmides de Impressão 3D' },
      { id: 'piramides-de-madeira', name: 'Pirâmides de Madeira' },
      { id: 'suportes-de-madeira', name: 'Suportes de Madeira' },
      { id: 'baterias-de-piramides', name: 'Baterias de Pirâmides' },
    ],
  },
  {
    id: 'cristais',
    name: 'Cristais',
    icon: 'Gem',
    subcategories: [
      { id: 'cristais', name: 'Cristais' },
      { id: 'materia-prima', name: 'Materia Prima' },
    ],
  },
  {
    id: 'incensos',
    name: 'Incensos',
    icon: 'Flame',
    subcategories: [
      { id: 'incensos', name: 'Incensos' },
      { id: 'incensarios', name: 'Incensários' },
      { id: 'essencias', name: 'Essências' },
      { id: 'difusores', name: 'Difusores' },
    ],
  },
  {
    id: 'acessorios',
    name: 'Acessórios',
    icon: 'Sparkles',
    subcategories: [
      { id: 'pingentes-e-brincos', name: 'Pingentes e Brincos' },
      { id: 'pulseiras', name: 'Pulseiras' },
      { id: 'pecas-em-prata', name: 'Peças em Prata' },
      { id: 'chaveiros', name: 'Chaveiros' },
      { id: 'porta-crachas', name: 'Porta Crachás' },
    ],
  },
  {
    id: 'radiestesia',
    name: 'Radiestesia',
    icon: 'Compass',
    subcategories: [
      { id: 'pendulos', name: 'Pêndulos' },
      { id: 'radiestesia', name: 'Radiestesia' },
      { id: 'bussolas', name: 'Bússolas' },
    ],
  },
  {
    id: 'religiosos',
    name: 'Religiosos',
    icon: 'Cross',
    subcategories: [
      { id: 'sao-francisco', name: 'São Francisco' },
      { id: 'joana-d-arc', name: 'Joana d\'Arc' },
      { id: 'cristo', name: 'Cristo' },
      { id: 'cruzes', name: 'Cruzes' },
      { id: 'egipcios', name: 'Egípcios' },
      { id: 'indianos', name: 'Indianos' },
    ],
  },
  {
    id: 'decoracao',
    name: 'Decoração',
    icon: 'Frame',
    subcategories: [
      { id: 'estatuas-e-enfeites', name: 'Estátuas e Enfeites' },
      { id: 'quadros', name: 'Quadros' },
      { id: 'fotos-e-porta-retratos', name: 'Fotos e Porta Retratos' },
      { id: 'velas-e-porta-velas', name: 'Velas e Porta Velas' },
      { id: 'papiros', name: 'Papiros' },
      { id: 'lampadas', name: 'Lâmpadas' },
      { id: 'pecas-em-aco-inox', name: 'Peças em Aço Inox' },
      { id: 'cadeiras', name: 'Cadeiras' },
    ],
  },
  {
    id: 'livros-e-midia',
    name: 'Livros e Mídia',
    icon: 'BookOpen',
    subcategories: [
      { id: 'livros', name: 'Livros' },
      { id: 'infantil', name: 'Infantil' },
      { id: 'filmes-dvd-s', name: 'Filmes DvD\'s' },
    ],
  },
  { id: 'novidades', name: 'Novidades', icon: 'Sparkles', featured: true, subcategories: [] },
];

export const PRODUCTS: Product[] = [
  {
    id: 'placa-de-cobre-m-1001',
    name: 'Placa de Cobre M',
    category: 'piramides',
    subcategory: 'baterias-de-piramides',
    categoryLabel: 'Baterias de Pirâmides',
    description: 'Placa de Cobre M — peça da linha Pirâmides da Quéops Pirâmides.',
    longDescription: 'Placa de Cobre para Bateria de Pirâmides M – 6 cm x 7cm Placa de cobre de alta qualidade, ideal para ser utilizada em baterias de pirâmides, otimizando o fluxo de energia. Perfeita para complementar a estrutura das pirâmides e potencializar seus efeitos. Dimensões: 6cm x 7cm x 0,091mm Material: Cobre Peso: Aproximadamente 0,1kg Fabricada pela Loja Quéops Pirâmides. Obs: Este link é exclusivamente para a aquisição da placa de cobre.',
    price: 17,
    tag: 'DESTAQUE',
    stock: 8,
    image: 'https://queopspiramides.com.br/wp-content/uploads/2026/04/1000641431.png',
    weight: '',
    sku: 'QP-1001',
  },
  {
    id: 'piramide-de-cobre-fechada-com-15cm-de-base-1002',
    name: 'Pirâmide de Cobre Fechada com 15cm de Base',
    category: 'piramides',
    subcategory: 'piramides-de-cobre',
    categoryLabel: 'Pirâmides de Cobre',
    description: 'Pirâmide de Cobre Fechada com 15cm de Base — peça da linha Pirâmides da Quéops Pirâmides.',
    longDescription: 'Pirâmide de Cobre com Base de Madeira – Energia, Estilo e Estabilidade Transforme seu ambiente com nossa pirâmide de cobre com base de madeira, projetada com medidas proporcionais à Grande Pirâmide de Quéops. Disponível em diversos tamanhos, incluindo a imponente versão de 50cm de base (5,5kg), ela oferece precisão, durabilidade e um design sofisticado. Tamanhos disponíveis: 10cm, 12cm, 15cm, 17cm, 20cm, 23cm, 25cm, 32cm, 35cm, 37cm, 40cm e 50cm. Alta qualidade: Chapa de cobre de 0,90mm com polimento e verniz, resistente à oxidação. Base firme: Fixada em madeira para máxima estabilidade e segu',
    price: 310,
    stock: 0,
    image: 'https://queopspiramides.com.br/wp-content/uploads/2026/04/1000670557.png',
    weight: '',
    sku: 'QP-1002',
  },
  {
    id: 'piramide-de-cobre-fechada-com-45cm-de-base-1003',
    name: 'Pirâmide de Cobre Fechada com 45cm de Base',
    category: 'piramides',
    subcategory: 'piramides-de-cobre',
    categoryLabel: 'Pirâmides de Cobre',
    description: 'Pirâmide de Cobre Fechada com 45cm de Base — peça da linha Pirâmides da Quéops Pirâmides.',
    longDescription: 'Pirâmide de Cobre com Base de Madeira – Energia, Estilo e Estabilidade Transforme seu ambiente com nossa pirâmide de cobre com base de madeira, projetada com medidas proporcionais à Grande Pirâmide de Quéops. Disponível em diversos tamanhos, incluindo a imponente versão de 50cm de base (5,5kg), ela oferece precisão, durabilidade e um design sofisticado. Tamanhos disponíveis: 10cm, 12cm, 17cm, 20cm, 23cm, 25cm, 32cm, 35cm, 37cm, 40cm e 50cm. Alta qualidade: Chapa de cobre de 0,90mm com polimento e verniz, resistente à oxidação. Base firme: Fixada em madeira para máxima estabilidade e segurança.',
    price: 1790,
    stock: 25,
    image: 'https://queopspiramides.com.br/wp-content/uploads/2026/04/1000670638.png',
    weight: '',
    sku: 'QP-1003',
  },
  {
    id: 'caixa-para-transporte-de-suporte-envio-aereo-g-1004',
    name: 'Caixa para Transporte de Suporte Envio Aéreo G',
    category: 'piramides',
    subcategory: 'piramides-de-cobre',
    categoryLabel: 'Pirâmides de Cobre',
    description: 'Caixa para Transporte de Suporte Envio Aéreo G — peça da linha Pirâmides da Quéops Pirâmides.',
    longDescription: 'Caixa de Transporte para Envio Aéreo G – Segurança e Praticidade em Cada Detalhe Nossa caixa transporta o Suporte com Regulagem de Altura ou o Suporte com 3 Regulagens. Com alça reforçada e rodízios que garantem mobilidade, ela é perfeita para facilitar deslocamentos. Versátil, também comporta outros itens, tornando-se ideal para quem busca praticidade em viagens ou envios aéreos. Escolha eficiência e proteção no transporte de seu Suporte! Caixa em MDF reforçado, ideal para transporte seguro do suporte. Estrutura resistente e funcional, indicada para envios por avião e longas distâncias. Possu',
    price: 280,
    stock: 25,
    image: 'https://queopspiramides.com.br/wp-content/uploads/2026/03/1000557757.png',
    weight: '',
    sku: 'QP-1004',
  },
  {
    id: 'conjunto-piramide-veludo-azul-e-suporte-suspenso-fixo-1005',
    name: 'Conjunto Pirâmide Veludo Azul e Suporte SUSPENSO FIXO',
    category: 'piramides',
    subcategory: 'piramides-de-veludo-azul',
    categoryLabel: 'Pirâmides de Veludo Azul',
    description: 'Conjunto Pirâmide Veludo Azul e Suporte SUSPENSO FIXO — peça da linha Pirâmides da Quéops Pirâmides.',
    longDescription: 'Conjunto de Pirâmide de Veludo Azul com Suporte Fixo – Harmonia e Durabilidade Sob Medida Transforme seu espaço com a energia e a precisão das pirâmides proporcionais à Grande Pirâmide de Quéops. Produzidas com chapa de mdf e proporcionais à Grande Pirâmide de Quéops, essas peças oferecem funcionalidade, segurança e acabamento premium. Disponíveis em: 50cm, 40cm, 37cm, 35cm Base em MDF de 0,3mm, interior revestido com cartolina laminada azul e cobertura externa em veludo cotelê azul. Criadas com exclusividade pela Quéops Pirâmides desde 1990, nosso design e técnica são garantia de qualidade e ',
    price: 704,
    stock: 25,
    image: 'https://queopspiramides.com.br/wp-content/uploads/2026/03/1774634707_ca5c48f281523a5ce87eb68e8b7b548b.png',
    weight: '',
    sku: 'QP-1005',
  },
  {
    id: 'conjunto-piramide-veludo-azul-e-suporte-suspenso-regulavel-1006',
    name: 'Conjunto Pirâmide Veludo Azul e Suporte SUSPENSO REGULÁVEL',
    category: 'piramides',
    subcategory: 'piramides-de-veludo-azul',
    categoryLabel: 'Pirâmides de Veludo Azul',
    description: 'Conjunto Pirâmide Veludo Azul e Suporte SUSPENSO REGULÁVEL — peça da linha Pirâmides da Quéops Pirâmides.',
    longDescription: 'Conjunto de Pirâmide de Veludo Azul com Suporte Suspenso Regulável – Ajuste Preciso para Energia Perfeita Experimente a praticidade e a harmonia com nosso conjunto de pirâmide de cobre em suporte suspenso regulável. Com altura ajustável, o suporte proporciona máxima versatilidade e conforto. Produzidas com chapa de mdf e proporcionais à Grande Pirâmide de Quéops, essas peças oferecem funcionalidade, segurança e acabamento premium. Disponíveis em: 50cm, 40cm, 37cm, 35cm Base em MDF de 0,3mm, interior revestido com cartolina laminada azul e cobertura externa em veludo cotelê azul. Desde 1990, a ',
    price: 992,
    stock: 25,
    image: 'https://queopspiramides.com.br/wp-content/uploads/2026/03/1774635607_cc7bedccfaf82f64eccb8d69b79da97a.png',
    weight: '',
    sku: 'QP-1006',
  },
  {
    id: 'conjunto-piramide-veludo-azul-e-suporte-com-3-regulagens-1007',
    name: 'Conjunto Pirâmide Veludo Azul e Suporte com 3 REGULAGENS',
    category: 'piramides',
    subcategory: 'piramides-de-veludo-azul',
    categoryLabel: 'Pirâmides de Veludo Azul',
    description: 'Conjunto Pirâmide Veludo Azul e Suporte com 3 REGULAGENS — peça da linha Pirâmides da Quéops Pirâmides.',
    longDescription: 'Conjunto de Pirâmide de Veludo Azul com Suporte com 3 Regulagens – Conforto, Versatilidade e Energia Aprimore sua experiência com a praticidade de um suporte que se ajusta perfeitamente ao seu ambiente. Com três regulagens, este suporte permite ajuste de altura e movimento para frente, sendo ideal para uso sobre camas, sofás ou poltronas. Produzidas com chapa de mdf e proporcionais à Grande Pirâmide de Quéops, essas peças oferecem funcionalidade, segurança e acabamento premium. Disponíveis em: 50cm, 40cm, 37cm, 35cm Base em MDF de 0,3mm, interior revestido com cartolina laminada azul e cobertu',
    price: 1730,
    stock: 25,
    image: 'https://queopspiramides.com.br/wp-content/uploads/2026/03/1774634704_735b278ddc37623a546b981c103456da.png',
    weight: '',
    sku: 'QP-1007',
  },
  {
    id: 'bateria-impressao-3d-azul-p-ref-cma-12-1008',
    name: 'Bateria Impressão 3D Azul P – Ref. CMA 12',
    category: 'piramides',
    subcategory: 'baterias-de-piramides',
    categoryLabel: 'Baterias de Pirâmides',
    description: 'Bateria Impressão 3D Azul P – Ref. CMA 12 — peça da linha Pirâmides da Quéops Pirâmides.',
    longDescription: 'Bateria Impressão 3D Azul P A bateria de pirâmides é projetada com medidas proporcionais à Pirâmide de Quéops, potencializando sua ação energética. Composta em impressão 3D e com uma placa de cobre, amplifica e direciona vibrações sutis para harmonização e revitalização. Ideal para terapias energéticas e reequilíbrio vibracional. Como usar: Norteie a bateria de pirâmides com uma bússola. Coloque a placa de cobre sobre a estrutura de pirâmides. Mantenha a placa por aproximadamente 8 horas antes de utilizá-la diretamente no corpo com esparadrapo. Após esse período, a placa descarrega e precisa s',
    price: 60,
    stock: 25,
    image: 'https://queopspiramides.com.br/wp-content/uploads/2026/06/1779837013_278b282982c5ae3d10859f00fdc8253f.png',
    weight: '',
    sku: 'QP-1008',
  },
  {
    id: 'bateria-impressao-3d-azul-m-ref-cma-11-1009',
    name: 'Bateria Impressão 3D Azul M – Ref. CMA 11',
    category: 'piramides',
    subcategory: 'baterias-de-piramides',
    categoryLabel: 'Baterias de Pirâmides',
    description: 'Bateria Impressão 3D Azul M – Ref. CMA 11 — peça da linha Pirâmides da Quéops Pirâmides.',
    longDescription: 'Bateria Impressão 3D Azul M A bateria de pirâmides é projetada com medidas proporcionais à Pirâmide de Quéops, potencializando sua ação energética. Composta em impressão 3D e com uma placa de cobre, amplifica e direciona vibrações sutis para harmonização e revitalização. Ideal para terapias energéticas e reequilíbrio vibracional. Como usar: Norteie a bateria de pirâmides com uma bússola. Coloque a placa de cobre sobre a estrutura de pirâmides. Mantenha a placa por aproximadamente 8 horas antes de utilizá-la diretamente no corpo com esparadrapo. Após esse período, a placa descarrega e precisa s',
    price: 85,
    stock: 25,
    image: 'https://queopspiramides.com.br/wp-content/uploads/2026/06/1779837011_278b282982c5ae3d10859f00fdc8253f.png',
    weight: '',
    sku: 'QP-1009',
  },
  {
    id: 'torre-selenita-p-12cm-1010',
    name: 'Torre Selenita P 12cm',
    category: 'cristais',
    subcategory: 'cristais',
    categoryLabel: 'Cristais',
    description: 'Torre Selenita P 12cm — peça da linha Cristais da Quéops Pirâmides.',
    longDescription: 'Torre em Selenita P com 10cm de Altura A Torre em Selenita &eacute; uma pe&ccedil;a que eleva a energia do ambiente e promove o equil&iacute;brio espiritual. Com 6 cm de altura e 2,5 cm de di&acirc;metro, &eacute; ideal para limpar e purificar energias, tanto de pessoas quanto de ambientes. Seu formato de torre tamb&eacute;m permite que outros cristais sejam colocados ao redor, sendo perfeita como centro de altar ou como elemento decorativo. Transforme sua decora&ccedil;&atilde;o combinando a Torre de Selenita com uma base de LED girat&oacute;ria para criar uma lumin&aacute;ria &uacute;nica, o',
    price: 67,
    tag: 'DESTAQUE',
    stock: 0,
    image: 'https://queopspiramides.com.br/wp-content/uploads/2026/03/1774655704_ebc7b372efd257d5191b0d2af5446f04.png',
    weight: '',
    sku: 'QP-1010',
  },
  {
    id: 'cruz-de-cristal-fume-20cm-1011',
    name: 'Cruz de Cristal Fumê 20cm',
    category: 'cristais',
    subcategory: 'cristais',
    categoryLabel: 'Cristais',
    description: 'Cruz de Cristal Fumê 20cm — peça da linha Cristais da Quéops Pirâmides.',
    longDescription: 'Cruz de Cristal Fumê com 20cm de Altura – Beleza e Espiritualidade Esta cruz de cristal fumê combina espiritualidade e elegância em uma peça de 20 cm de altura. Com lapidação impecável e a profundidade característica do quartzo fumê, é perfeita para compor altares, mesas laterais ou decorar ambientes com um toque de sofisticação e proteção. Destaques: Material: Cristal de quartzo fumê natural de alta qualidade. Dimensões: 20 cm de altura Estilo: Design clean que se adapta a decorações clássicas e modernas. Energia: O cristal fumê é conhecido por suas propriedades de aterramento e purificação. ',
    price: 1800,
    stock: 25,
    image: 'https://queopspiramides.com.br/wp-content/uploads/2026/03/IMG-20260311-WA0088.png',
    weight: '',
    sku: 'QP-1011',
  },
  {
    id: 'cristal-rolado-hematita-6-1012',
    name: 'Cristal Rolado Hematita 6',
    category: 'cristais',
    subcategory: 'cristais',
    categoryLabel: 'Cristais',
    description: 'Cristal Rolado Hematita 6 — peça da linha Cristais da Quéops Pirâmides.',
    longDescription: 'Hematita Rolada – Pedra Natural de Aterramento e Proteção A Hematita Rolada é um cristal de alta densidade e brilho metálico, sendo a escolha ideal para quem busca um poderoso aterramento energético, proteção espiritual e fortalecimento pessoal. Com seu acabamento liso e peso característico, é perfeita para ser carregada no bolso ou na bolsa como um amuleto diário de força. Benefícios e Propriedades Energéticas Aterramento (Grounding): Conecta profundamente com as energias da Terra, promovendo estabilidade e segurança. Proteção Psíquica: Cria um escudo robusto que dissipa a negatividade e impe',
    price: 6,
    stock: 25,
    image: 'https://queopspiramides.com.br/wp-content/uploads/2026/03/1772643006_8857bafeaad76145c4cbdcc4722dfb8f.png',
    weight: '',
    sku: 'QP-1012',
  },
  {
    id: 'papel-presente-venda-1013',
    name: 'Papel Presente VENDA',
    category: 'cristais',
    subcategory: 'materia-prima',
    categoryLabel: 'Materia Prima',
    description: 'Papel Presente VENDA — peça da linha Cristais da Quéops Pirâmides.',
    longDescription: 'Papel Presente VENDA — peça da linha Cristais da Quéops Pirâmides.',
    price: 2.5,
    stock: 25,
    image: 'https://queopspiramides.com.br/wp-content/uploads/2026/03/1774518607_8e04054b8e51ed490ecd84232752e623.png',
    weight: '',
    sku: 'QP-1013',
  },
  {
    id: 'fita-presente-venda-1014',
    name: 'Fita Presente VENDA',
    category: 'cristais',
    subcategory: 'materia-prima',
    categoryLabel: 'Materia Prima',
    description: 'Fita Presente VENDA — peça da linha Cristais da Quéops Pirâmides.',
    longDescription: 'Fita Presente VENDA — peça da linha Cristais da Quéops Pirâmides.',
    price: 0.5,
    stock: 25,
    image: 'https://queopspiramides.com.br/wp-content/uploads/2026/03/1774520112_b1429b36865f98ad976ac4cf022809e2.png',
    weight: '',
    sku: 'QP-1014',
  },
  {
    id: 'coracao-cristal-quartzo-azul-65-1015',
    name: 'Coração Cristal Quartzo Azul 65',
    category: 'cristais',
    subcategory: 'cristais',
    categoryLabel: 'Cristais',
    description: 'Coração Cristal Quartzo Azul 65 — peça da linha Cristais da Quéops Pirâmides.',
    longDescription: 'Cristais em Formato de Coração – Energia e Amor em Cada Detalhe O quartzo azul é a pedra da comunicação e da calma profunda. Sua energia é de tranquilidade e clareza, agindo para silenciar a mente, reduzir medos e favorecer a expressão pessoal. É o cristal do relaxamento, da paciência e da paz espiritual. Carregue a energia dos cristais com nossos corações, cada um com suas propriedades únicas. Ideal para presentear ou decorar, estes cristais em formato de coração trazem amor e positividade para o seu dia a dia. Como usar Utilize para decoração, meditação ou presentear pessoas especiais Escolh',
    price: 65,
    stock: 25,
    image: 'https://queopspiramides.com.br/wp-content/uploads/2025/09/1758719115_8a7cbe51c7cdf08b45ac96bcc78f952e.png',
    weight: '',
    sku: 'QP-1015',
  },
  {
    id: 'coracao-cristal-quartzo-verde-25-1016',
    name: 'Coração Cristal Quartzo Verde 25',
    category: 'cristais',
    subcategory: 'cristais',
    categoryLabel: 'Cristais',
    description: 'Coração Cristal Quartzo Verde 25 — peça da linha Cristais da Quéops Pirâmides.',
    longDescription: 'Cristais em Formato de Coração – Energia e Amor em Cada Detalhe O quartzo verde é a pedra da cura e da vitalidade da natureza. Sua energia é de equilíbrio e rejuvenescimento, agindo para acalmar as emoções, fortalecer a saúde física e atrair prosperidade. É o cristal da esperança, da estabilidade e do bem-estar. Carregue a energia dos cristais com nossos corações, cada um com suas propriedades únicas. Ideal para presentear ou decorar, estes cristais em formato de coração trazem amor e positividade para o seu dia a dia. Como usar Utilize para decoração, meditação ou presentear pessoas especiais',
    price: 25,
    stock: 25,
    image: 'https://queopspiramides.com.br/wp-content/uploads/2026/03/1772060412_8a7cbe51c7cdf08b45ac96bcc78f952e.png',
    weight: '',
    sku: 'QP-1016',
  },
  {
    id: 'coracao-cristal-quartzo-cristal-120-1017',
    name: 'Coração Cristal Quartzo Cristal 120',
    category: 'cristais',
    subcategory: 'cristais',
    categoryLabel: 'Cristais',
    description: 'Coração Cristal Quartzo Cristal 120 — peça da linha Cristais da Quéops Pirâmides.',
    longDescription: 'Cristais em Formato de Coração – Energia e Amor em Cada Detalhe O quartzo cristal é o mestre da cura e o amplificador de energia universal. Sua energia é de purificação e clareza, agindo para desbloquear canais energéticos, potencializar a força de outros cristais e harmonizar a mente. É o cristal da luz, do foco e da vitalidade. Carregue a energia dos cristais com nossos corações, cada um com suas propriedades únicas. Ideal para presentear ou decorar, estes cristais em formato de coração trazem amor e positividade para o seu dia a dia. Como usar Utilize para decoração, meditação ou presentear',
    price: 120,
    stock: 25,
    image: 'https://queopspiramides.com.br/wp-content/uploads/2026/03/1772060109_8a7cbe51c7cdf08b45ac96bcc78f952e.png',
    weight: '',
    sku: 'QP-1017',
  },
  {
    id: 'coracao-cristal-quartzo-cristal-65-1018',
    name: 'Coração Cristal Quartzo Cristal 65',
    category: 'cristais',
    subcategory: 'cristais',
    categoryLabel: 'Cristais',
    description: 'Coração Cristal Quartzo Cristal 65 — peça da linha Cristais da Quéops Pirâmides.',
    longDescription: 'Cristais em Formato de Coração – Energia e Amor em Cada Detalhe O quartzo cristal é o mestre da cura e o amplificador de energia universal. Sua energia é de purificação e clareza, agindo para desbloquear canais energéticos, potencializar a força de outros cristais e harmonizar a mente. É o cristal da luz, do foco e da vitalidade. Carregue a energia dos cristais com nossos corações, cada um com suas propriedades únicas. Ideal para presentear ou decorar, estes cristais em formato de coração trazem amor e positividade para o seu dia a dia. Como usar Utilize para decoração, meditação ou presentear',
    price: 65,
    stock: 25,
    image: 'https://queopspiramides.com.br/wp-content/uploads/2026/03/1772060108_8a7cbe51c7cdf08b45ac96bcc78f952e.png',
    weight: '',
    sku: 'QP-1018',
  },
  {
    id: 'incenso-darshan-nossa-senhora-desatadora-de-nos-1019',
    name: 'Incenso Darshan – Nossa Senhora Desatadora de Nós',
    category: 'incensos',
    subcategory: 'incensos',
    categoryLabel: 'Incensos',
    description: 'Incenso Darshan – Nossa Senhora Desatadora de Nós — peça da linha Incensos da Quéops Pirâmides.',
    longDescription: 'Incenso Indiano de Carvão Darshan – Nossa Senhora Desatadora de Nós Este incenso tem como objetivo trazer uma sensação de alívio, clareza e assistência divina. Seu aroma calmante e purificador, com perfume acentuado de rosas, é ideal para momentos de meditação, oração. O aroma suave, porém envolvente, é perfeito para criar um ambiente de tranquilidade e reflexão. História: Este incenso faz homenagem a uma devoção que surgiu na Alemanha no século XVIII e foi trazida para a América Latina pelo Papa Francisco, simbolizando a intercessão de Nossa Senhora Desatadora de Nós para resolver situações d',
    price: 4,
    tag: 'DESTAQUE',
    stock: 0,
    image: 'https://queopspiramides.com.br/wp-content/uploads/2026/05/1000631104.png',
    weight: '',
    sku: 'QP-1019',
  },
  {
    id: 'incenso-darshan-sal-grosso-1020',
    name: 'Incenso Darshan – Sal Grosso',
    category: 'incensos',
    subcategory: 'incensos',
    categoryLabel: 'Incensos',
    description: 'Incenso Darshan – Sal Grosso — peça da linha Incensos da Quéops Pirâmides.',
    longDescription: 'Incenso Indiano de Carvão Darshan Sal Grosso O incenso de sal grosso é usado para purificar ambientes, afastar energias desarmônicas e combater o mau olhado e a inveja. Ideal para energizar e proteger o ambiente, criando uma atmosfera harmoniosa e propícia à meditação e ao relaxamento. Incenso de carvão vegetal é extraído da natureza e não possui produtos químicos e tóxicos. Contém: vareta de bambú, pó de sândalo, ervas e essências. País de Origem: Índia Fabricante: Darshan Tempo de Queima: aproximadamente 40 minutos Quantidade: 8 varetas Perfeito para quem busca uma fragrância espiritual e pu',
    price: 4,
    stock: 25,
    image: 'https://queopspiramides.com.br/wp-content/uploads/2026/06/1779226212_1ae738c16738451e668678a645d8a85f.png',
    weight: '',
    sku: 'QP-1020',
  },
  {
    id: 'incenso-darshan-flor-de-maracuja-1021',
    name: 'Incenso Darshan – Flor de Maracujá',
    category: 'incensos',
    subcategory: 'incensos',
    categoryLabel: 'Incensos',
    description: 'Incenso Darshan – Flor de Maracujá — peça da linha Incensos da Quéops Pirâmides.',
    longDescription: 'Incenso Indiano de Carvão Darshan Flor de Maracujá O incenso de Flor de Maracujá, ou Passiflora, é um poderoso aliado do bem-estar que une propriedades terapêuticas e espirituais para reduzir a ansiedade, combater a insônia e relaxar o corpo, enquanto promove a paz interior, a harmonia familiar e a clareza mental através de seu aroma suave e serenador. Incenso de carvão vegetal é extraído da natureza e não possui produtos químicos e tóxicos. Contém: vareta de bambú, pó de sândalo, ervas e essências. País de Origem: Índia Fabricante: Darshan Tempo de Queima: aproximadamente 40 minutos Quantidad',
    price: 4,
    stock: 25,
    image: 'https://queopspiramides.com.br/wp-content/uploads/2026/06/1779226219_1cc6c9e747c4acf1d4830352208df1da.png',
    weight: '',
    sku: 'QP-1021',
  },
  {
    id: 'incensario-latao-m-1022',
    name: 'Incensário Latão M',
    category: 'incensos',
    subcategory: 'incensarios',
    categoryLabel: 'Incensários',
    description: 'Incensário Latão M — peça da linha Incensos da Quéops Pirâmides.',
    longDescription: 'Incensário em Latão M 9cm O incensário de latão para 3 varetas é perfeito para quem deseja intensificar a aromatização e a energia do ambiente. Cada peça é única e funcional, as cinzas caem dentro da peça. Tamanhos Aproximadas: 9cm de diâmetro e 2cm de altura Material: Latão Capacidade: 3 varetas Peso: 20g',
    price: 60,
    stock: 2,
    image: 'https://queopspiramides.com.br/wp-content/uploads/2026/05/1779227109_c2a1b2d693b62438a2fc92795afddd7c.png',
    weight: '',
    sku: 'QP-1022',
  },
  {
    id: 'incensario-latao-g-1023',
    name: 'Incensário Latão G',
    category: 'incensos',
    subcategory: 'incensarios',
    categoryLabel: 'Incensários',
    description: 'Incensário Latão G — peça da linha Incensos da Quéops Pirâmides.',
    longDescription: 'Incensário em Latão G 14,5cm O incensário de latão para 3 varetas é perfeito para quem deseja intensificar a aromatização e a energia do ambiente. Cada peça é única e funcional, as cinzas caem dentro da peça. Tamanhos Aproximadas: 14,5cm de diâmetro e 2cm de altura Material: Latão Capacidade: 3 varetas Peso: 60g',
    price: 78,
    stock: 25,
    image: 'https://queopspiramides.com.br/wp-content/uploads/2026/04/1774974605_c2a1b2d693b62438a2fc92795afddd7c.png',
    weight: '',
    sku: 'QP-1023',
  },
  {
    id: 'incensario-vidro-65-1024',
    name: 'Incensário Vidro 65',
    category: 'incensos',
    subcategory: 'incensarios',
    categoryLabel: 'Incensários',
    description: 'Incensário Vidro 65 — peça da linha Incensos da Quéops Pirâmides.',
    longDescription: 'Incensário Diversos Modelos Incensários artesanais variados, ideais para queimar incensos com segurança e estilo. Disponíveis em diferentes formatos, cores e tamanhos, são perfeitos para decoração de espaços espirituais, altares e ambientes de meditação. Cada peça é única e funcional, atendendo desde uma até três varetas, conforme o modelo. Tamanhos e capacidade: variam conforme o modelo Material: diversos (consultar disponibilidade) Capacidade: 1 ou 3 varetas Para escolher, entre em contato e enviaremos fotos atualizadas das peças disponíveis.',
    price: 65,
    stock: 25,
    image: 'https://queopspiramides.com.br/wp-content/uploads/2026/03/1774483815_afc319a78c357aa838769331a043b6b4.png',
    weight: '',
    sku: 'QP-1024',
  },
  {
    id: 'difusor-lua-cheia-1025',
    name: 'Difusor Lua Cheia',
    category: 'incensos',
    subcategory: 'difusores',
    categoryLabel: 'Difusores',
    description: 'Difusor Lua Cheia — peça da linha Incensos da Quéops Pirâmides.',
    longDescription: 'Difusor Umidificador e Luminária Lua Cheia Suporta até 800ml de água, com cores inspiradas na Lua – branco, amarelo, laranja – e alternância automática entre diversas tonalidades. Dimensões: 15cm x 15cm. Difusor ultrassônico que fragmenta água e óleos essenciais em micropartículas, liberando vapor frio sem alterar propriedades aromáticas. Umidifica e aromatiza o ambiente, ideal para aliviar crises alérgicas e desconforto no tempo seco. Silencioso, econômico e portátil. Conta com LED cromoterapia em RGB com troca de cor automática. Especificações: Capacidade: 800ml Material: Plástico ABS + PP D',
    price: 117,
    stock: 0,
    image: 'https://queopspiramides.com.br/wp-content/uploads/2026/06/1774504218_a5a103ebcb34c2a3f68d905253589845.png',
    weight: '',
    sku: 'QP-1025',
  },
  {
    id: 'difusor-ceramica-bivolt-1026',
    name: 'Difusor Cerâmica Bivolt',
    category: 'incensos',
    subcategory: 'difusores',
    categoryLabel: 'Difusores',
    description: 'Difusor Cerâmica Bivolt — peça da linha Incensos da Quéops Pirâmides.',
    longDescription: 'Difusor Elétrico de Cerâmica Bivolt Difusor elétrico compacto e eficiente, ideal para aromatizar ambientes. Equipado com resistência em cerâmica, garante aquecimento seguro e contínuo. O plug giratório permite melhor ajuste na tomada. Dimensões: 11cm x 5cm x 6cm (altura) Material: Cerâmica Bivolt automático, 10W de potência, cobre até 20m². Fácil de usar, prático e discreto.',
    price: 84,
    stock: 25,
    image: 'https://queopspiramides.com.br/wp-content/uploads/2026/03/1774504220_a68e2a797a53af0179e05812a6b14f56.png',
    weight: '',
    sku: 'QP-1026',
  },
  {
    id: 'essencia-15ml-1027',
    name: 'Essência 15ml',
    category: 'incensos',
    subcategory: 'essencias',
    categoryLabel: 'Essências',
    description: 'Essência 15ml — peça da linha Incensos da Quéops Pirâmides.',
    longDescription: 'Essência 15ml — peça da linha Incensos da Quéops Pirâmides.',
    price: 30,
    stock: 0,
    image: 'https://queopspiramides.com.br/wp-content/uploads/2026/03/1774505409_c6d6221e0e51ca9c79b86ac08fe6c54d.png',
    weight: '',
    sku: 'QP-1027',
  },
  {
    id: 'chaveiro-nossa-senhora-aparecida-azul-e-dourado-1028',
    name: 'Chaveiro Nossa Senhora Aparecida Azul e Dourado',
    category: 'acessorios',
    subcategory: 'chaveiros',
    categoryLabel: 'Chaveiros',
    description: 'Chaveiro Nossa Senhora Aparecida Azul e Dourado — peça da linha Acessórios da Quéops Pirâmides.',
    longDescription: 'Chaveiro Metal Nossa Senhora Aparecida – Símbolo de Amor e Proteção Este delicado chaveiro em metal de Nossa Senhora Aparecida é um símbolo de devoção que carrega o amor materno da Padroeira, oferecendo proteção e carinho em cada detalhe do seu dia a dia Como usar Utilize como chaveiro para carregar a simbologia de Nossa Senhora Ideal para uso pessoal ou como presente significativo. Especificações Material: Zamak Dimensões: Argola 2,5 cm x Pingente 4 cm Cor: Dourado',
    price: 45,
    tag: 'DESTAQUE',
    stock: 25,
    image: 'https://queopspiramides.com.br/wp-content/uploads/2026/05/1000629643.png',
    weight: '',
    sku: 'QP-1028',
  },
  {
    id: 'corrente-prata-70cm-ref-19587-1029',
    name: 'Corrente Prata 70cm – Ref. 19587',
    category: 'acessorios',
    subcategory: 'pecas-em-prata',
    categoryLabel: 'Peças em Prata',
    description: 'Corrente Prata 70cm – Ref. 19587 — peça da linha Acessórios da Quéops Pirâmides.',
    longDescription: 'Corrente de Prata com Elos 70 cm &ndash; Qualidade e Sofistica&ccedil;&atilde;o Corrente de Prata 925 modelo 19587, com elos quadrados que conferem um design moderno e elegante. Pe&ccedil;a em prata clara, ideal para uso di&aacute;rio ou composi&ccedil;&atilde;o com pingentes. Confeccionada em Prata 925 de alta qualidade, garantindo durabilidade e resist&ecirc;ncia. Comprimento de 70 cm e largura de 0,1 cm. Acompanha certificado de garantia vital&iacute;cia pela autenticidade da prata. Ref. 19587',
    price: 522,
    stock: 1,
    image: 'https://queopspiramides.com.br/wp-content/uploads/2026/05/1778604610_7a4161a8e6f80cec76cad5e61ca3d020.png',
    weight: '',
    sku: 'QP-1029',
  },
  {
    id: 'pingente-cruz-prata-zirconia-vazada-1-5cm-ref-64691-1030',
    name: 'Pingente Cruz Prata Zircônia Vazada 1,5cm – Ref. 64691',
    category: 'acessorios',
    subcategory: 'pecas-em-prata',
    categoryLabel: 'Peças em Prata',
    description: 'Pingente Cruz Prata Zircônia Vazada 1,5cm – Ref. 64691 — peça da linha Acessórios da Quéops Pirâmides.',
    longDescription: 'Pingente de Prata Cruz, com 1,5cm, confeccionado em prata 925. Este pingente de cruz em prata 925 é uma peça robusta e significativa, ideal para quem busca representar sua fé de forma imponente e elegante. Seu design detalhado e imponente faz desta peça uma excelente escolha para expressar proteção e devoção. Zircônia: é uma pedra feita em laboratório e é a melhor imitação do Diamante. Muito conhecida pelo seu brilho podendo ter várias cores. A joia possui formato de uma cruz com 36 Pedras de Zircônia transparente e detalhes vazados. Altura: 1 cm Largura: 1,5 cm x 1,1cm Acompanha certificado d',
    price: 196,
    stock: 2,
    image: 'https://queopspiramides.com.br/wp-content/uploads/2026/06/1779319511_105b752e17585e387df00c08f29bc06c.png',
    weight: '',
    sku: 'QP-1030',
  },
  {
    id: 'pingente-prata-olho-de-horus-0-9cm-ref-68000-1031',
    name: 'Pingente Prata Olho de Horus 0,9cm – Ref. 68000',
    category: 'acessorios',
    subcategory: 'pecas-em-prata',
    categoryLabel: 'Peças em Prata',
    description: 'Pingente Prata Olho de Horus 0,9cm – Ref. 68000 — peça da linha Acessórios da Quéops Pirâmides.',
    longDescription: 'Pingente de Prata Cruz, com 1cm, confeccionado em prata 925. Joia vazada em formato de Olho de Hórus, composta por 1 pedra de Zircônia transparente. O Olho de Hórus é um símbolo que surgiu no Antigo Egito, como parte da mitologia. Assim como o nome sugere, o símbolo reproduz o olhar de Hórus, um dos deuses que os egípcios cultuavam Zircônia: é uma pedra feita em laboratório e é a melhor imitação do Diamante. Muito conhecida pelo seu brilho podendo ter várias cores. Altura: 0,9 cm Largura: 0,8 cm Acompanha certificado de garantia vitalícia pela autenticidade da prata 925. Obs: Corrente não acom',
    price: 110,
    stock: 1,
    image: 'https://queopspiramides.com.br/wp-content/uploads/2026/05/1779319512_542d8e04198f2a90674c3acbad48f297.png',
    weight: '',
    sku: 'QP-1031',
  },
  {
    id: 'pulseira-cristal-brilha-no-escuro-28-1032',
    name: 'Pulseira Cristal Brilha no Escuro 28',
    category: 'acessorios',
    subcategory: 'pulseiras',
    categoryLabel: 'Pulseiras',
    description: 'Pulseira Cristal Brilha no Escuro 28 — peça da linha Acessórios da Quéops Pirâmides.',
    longDescription: 'Pulseira de "Pedra Luminosa" Sintética – Brilho no Escuro Descrição: Este pingente é feito de material sintético (geralmente resina ou vidro) que incorpora compostos fotoluminescentes, como o aluminato de estrôncio. Absorve a luz natural ou artificial e a libera lentamente, produzindo um brilho visível no escuro após a exposição à luz. Destaque: O efeito de fosforescência é o grande atrativo, criando um visual único e chamativo que "acende" quando as luzes se apagam. Dica de Uso: Use esta pulseira no dia a dia para manter sua frequência energética elevada e protegida. Ela é perfeita para momen',
    price: 28,
    stock: 25,
    image: 'https://queopspiramides.com.br/wp-content/uploads/2026/05/1774464012_d4eab1981b4d639cefe7d85906476abc.png',
    weight: '',
    sku: 'QP-1032',
  },
  {
    id: 'pulseira-cristal-calcedonia-30-1033',
    name: 'Pulseira Cristal Calcedônia 30',
    category: 'acessorios',
    subcategory: 'pulseiras',
    categoryLabel: 'Pulseiras',
    description: 'Pulseira Cristal Calcedônia 30 — peça da linha Acessórios da Quéops Pirâmides.',
    longDescription: 'Pulseira de Calcedônia – Equilíbrio e Comunicação Descrição: A Calcedônia é uma gema de harmonização que promove a fraternidade e a paz interior. Ela atua absorvendo vibrações negativas e dissipando sentimentos de hostilidade, sendo essencial para quem busca estabilidade emocional e um espírito sereno. É o cristal ideal para alinhar mente e corpo em momentos de estresse. Destaque: Sua força reside no estímulo à comunicação clara e à expressão da verdade com suavidade. Ela ajuda a transformar a melancolia em alegria, facilitando o entendimento nos relacionamentos e fortalecendo a autoconfiança.',
    price: 30,
    stock: 25,
    image: 'https://queopspiramides.com.br/wp-content/uploads/2026/03/1772568007_d4eab1981b4d639cefe7d85906476abc.png',
    weight: '',
    sku: 'QP-1033',
  },
  {
    id: 'pulseira-cristal-quartzo-cristal-fume-30-1034',
    name: 'Pulseira Cristal Quartzo Cristal Fumê 30',
    category: 'acessorios',
    subcategory: 'pulseiras',
    categoryLabel: 'Pulseiras',
    description: 'Pulseira Cristal Quartzo Cristal Fumê 30 — peça da linha Acessórios da Quéops Pirâmides.',
    longDescription: 'Pulseira de Quartzo Fumê – Proteção e Aterramento Descrição: O Quartzo Fumê é uma das pedras mais potentes para ancoragem e proteção energética. Ele atua neutralizando vibrações negativas e transmutando energias densas, sendo essencial para quem busca estabilidade emocional e conexão com a terra. É um cristal que absorve o estresse, promovendo um ambiente de calma e segurança. Destaque: Sua principal característica é o alívio emocional e o desapego de padrões negativos. Ele ajuda a dissipar o medo e a ansiedade, trazendo foco e clareza prática para o cotidiano. Funciona como um escudo protetor',
    price: 30,
    stock: 25,
    image: 'https://queopspiramides.com.br/wp-content/uploads/2026/03/1772566808_d4eab1981b4d639cefe7d85906476abc.png',
    weight: '',
    sku: 'QP-1034',
  },
  {
    id: 'pingente-cristal-abalone-40-1035',
    name: 'Pingente Cristal Abalone 40',
    category: 'acessorios',
    subcategory: 'pingentes-e-brincos',
    categoryLabel: 'Pingentes e Brincos',
    description: 'Pingente Cristal Abalone 40 — peça da linha Acessórios da Quéops Pirâmides.',
    longDescription: 'Pingente de Abalone Abalone não é um mineral, mas sim uma concha de origem orgânica proveniente de um molusco marinho do gênero Haliotis. Ela é mundialmente valorizada por sua camada interna de madrepérola iridescente, que exibe um brilho intenso em tons de azul, verde, rosa e roxo. É considerada um "portal" para a harmonia, ajudando a elevar a vibração e a purificar ambientes. Seu uso é associado à calma e à paz interior, sendo ideal para momentos de estresse ou sobrecarga emocional. Atua como um escudo energético que protege e guia os pensamentos de quem a carrega, especialmente quando usada',
    price: 40,
    stock: 25,
    image: 'https://queopspiramides.com.br/wp-content/uploads/2026/03/1771962305_8002c2dda5a1b133a27566679045dd0f.png',
    weight: '',
    sku: 'QP-1035',
  },
  {
    id: 'pingente-cristal-ametista-112-1036',
    name: 'Pingente Cristal Ametista 112',
    category: 'acessorios',
    subcategory: 'pingentes-e-brincos',
    categoryLabel: 'Pingentes e Brincos',
    description: 'Pingente Cristal Ametista 112 — peça da linha Acessórios da Quéops Pirâmides.',
    longDescription: 'Pingente de Ametista – Transmutação e Equilíbrio Espiritual Descrição: A Ametista é um dos cristais mais venerados do mundo, conhecida como a pedra da transmutação energética. Ela possui uma vibração altamente espiritual que ajuda a converter energias negativas em vibrações positivas de amor e proteção. É um cristal que acalma a mente, favorece a meditação e ajuda a elevar os estados de consciência, sendo perfeita para momentos de transição e crescimento interior. Destaque: Sua principal característica é a poderosa conexão com o Chakra Frontal (Terceiro Olho) e o Coronário. Ela estimula a intu',
    price: 112,
    stock: 25,
    image: 'https://queopspiramides.com.br/wp-content/uploads/2026/04/1774467011_8002c2dda5a1b133a27566679045dd0f.png',
    weight: '',
    sku: 'QP-1036',
  },
  {
    id: 'bussola-internacional-1037',
    name: 'Bússola Internacional',
    category: 'radiestesia',
    subcategory: 'bussolas',
    categoryLabel: 'Bússolas',
    description: 'Bússola Internacional — peça da linha Radiestesia da Quéops Pirâmides.',
    longDescription: 'Bússola com Norte Magnético e Verdadeiro Internacional – Orientação Precisa para Suas Medições Nossas bússolas apontam o norte verdadeiro em vários locais do mundo! Entre em contato e escolha a sua. Obtenha medições precisas com nossa bússola que indica tanto o norte magnético quanto o verdadeiro. Ideal para orientar pirâmides, esta bússola é uma ferramenta essencial para quem busca precisão. Como usar Aponte a agulha da bússola para o norte magnético Posicione a pirâmide no norte verdadeiro Lembre-se o Norte magnético é para onde aponta a agulha da bússola O norte verdadeiro aponta para o nor',
    price: 48,
    tag: 'DESTAQUE',
    stock: 25,
    image: 'https://queopspiramides.com.br/wp-content/uploads/2026/05/1779226221_c83b9218773f274d0a72e901d550b78c.png',
    weight: '',
    sku: 'QP-1037',
  },
  {
    id: 'adesivo-grafico-radiestesia-yoshua-gg-11cm-1038',
    name: 'Adesivo Gráfico Radiestesia Yoshua GG – 11cm',
    category: 'radiestesia',
    subcategory: 'radiestesia',
    categoryLabel: 'Radiestesia',
    description: 'Adesivo Gráfico Radiestesia Yoshua GG – 11cm — peça da linha Radiestesia da Quéops Pirâmides.',
    longDescription: 'Gráfico Radiestésico Yoshua (Tamanho GG) – Adesivo de Proteção e Equilíbrio Adesivo radiônico utilizado para harmonizar e proteger pessoas e bens materiais. Dimensões: 7cm x 11cm Apresenta o nome original de Jesus Cristo em hebraico, um poderoso símbolo de proteção e força espiritual. Ideal para aplicação em ambientes, objetos ou uso pessoal.',
    price: 2,
    stock: 25,
    image: 'https://queopspiramides.com.br/wp-content/uploads/2026/01/1769720708_1ee2259c7668e08cd345abfb16093eb1.png',
    weight: '',
    sku: 'QP-1038',
  },
  {
    id: 'adesivo-grafico-radiestesia-yoshua-g-6-5cm-1039',
    name: 'Adesivo Gráfico Radiestesia Yoshua G – 6,5cm',
    category: 'radiestesia',
    subcategory: 'radiestesia',
    categoryLabel: 'Radiestesia',
    description: 'Adesivo Gráfico Radiestesia Yoshua G – 6,5cm — peça da linha Radiestesia da Quéops Pirâmides.',
    longDescription: 'Gráfico Radiestésico Yoshua (Tamanho G) – Adesivo de Proteção e Equilíbrio Adesivo radiônico utilizado para harmonizar e proteger pessoas e bens materiais. Dimensões: 4,5cm x 6,5cm Apresenta o nome original de Jesus Cristo em hebraico, um poderoso símbolo de proteção e força espiritual. Ideal para aplicação em ambientes, objetos ou uso pessoal.',
    price: 2,
    stock: 25,
    image: 'https://queopspiramides.com.br/wp-content/uploads/2026/04/1774481704_1ee2259c7668e08cd345abfb16093eb1.png',
    weight: '',
    sku: 'QP-1039',
  },
  {
    id: 'adesivo-grafico-radiestesia-9-circulos-g-6-5cm-1040',
    name: 'Adesivo Gráfico Radiestesia 9 Círculos G – 6,5cm',
    category: 'radiestesia',
    subcategory: 'radiestesia',
    categoryLabel: 'Radiestesia',
    description: 'Gráfico Radiestésico 9 Círculos – Adesivo de Proteção e Equilíbrio Adesivo radiônico utilizado para harmonizar e equilibrar energias indesejáveis em pessoas, animais e ambientes. D',
    longDescription: 'Gráfico Radiestésico 9 Círculos (Tamanho G) – Adesivo de Proteção e Equilíbrio Adesivo radiônico utilizado para harmonizar e equilibrar energias indesejáveis em pessoas, animais e ambientes. Dimensões: 6,5cm x 6,5cm Representa a vibração dos 9 principais arcanjos, promovendo proteção energética. Ideal para aplicação discreta em casas, escritórios ou automóveis.',
    price: 2,
    stock: 25,
    image: 'https://queopspiramides.com.br/wp-content/uploads/2026/04/1774482011_58303d6622505d2bba398b8feea7a6e5.png',
    weight: '',
    sku: 'QP-1040',
  },
  {
    id: 'pendulo-egipcio-quartzo-rosa-1041',
    name: 'Pêndulo Egípcio – Quartzo Rosa',
    category: 'radiestesia',
    subcategory: 'pendulos',
    categoryLabel: 'Pêndulos',
    description: 'Pêndulo Egípcio – Quartzo Rosa — peça da linha Radiestesia da Quéops Pirâmides.',
    longDescription: 'Pêndulo Quartzo Rosa Ponta Egípcio com Corrente O Pêndulo Quartzo Rosa Egípcio é um instrumento de radiestesia utilizado para obter respostas intuitivas e auxiliar no autoconhecimento. Com formato em ponta, proporciona precisão em práticas de análise energética. O Pêndulo de Quartzo Rosa é capaz de proporcionar clareza e orientação, canalizando energias para revelar respostas com precisão e profundidade Para utilizá-lo, segure a corrente e concentre-se em sua pergunta. O movimento do pêndulo indicará a resposta desejada, auxiliando no processo de percepção e equilíbrio pessoal. Tamanho: 4 cm M',
    price: 48,
    stock: 0,
    image: 'https://queopspiramides.com.br/wp-content/uploads/2026/01/1764432905_4a3d0b7a33a8a145d93afb9334545873.png',
    weight: '',
    sku: 'QP-1041',
  },
  {
    id: 'pendulo-egipcio-ametista-1042',
    name: 'Pêndulo Egípcio – Ametista',
    category: 'radiestesia',
    subcategory: 'pendulos',
    categoryLabel: 'Pêndulos',
    description: 'Pêndulo Egípcio – Ametista — peça da linha Radiestesia da Quéops Pirâmides.',
    longDescription: 'Pêndulo Ametista Ponta Egípcio com Corrente O Pêndulo Ametista Egípcio é um instrumento de radiestesia utilizado para obter respostas intuitivas e auxiliar no autoconhecimento. Com formato em ponta, proporciona precisão em práticas de análise energética. O Pêndulo de Ametista é capaz de proporcionar clareza e orientação, canalizando energias para revelar respostas com precisão e profundidade Para utilizá-lo, segure a corrente e concentre-se em sua pergunta. O movimento do pêndulo indicará a resposta desejada, auxiliando no processo de percepção e equilíbrio pessoal. Tamanho: 4 cm Material: Cri',
    price: 48,
    stock: 0,
    image: 'https://queopspiramides.com.br/wp-content/uploads/2026/04/1774483210_7a04dd8df951b2945a6cf2574fdbb22f.png',
    weight: '',
    sku: 'QP-1042',
  },
  {
    id: 'pendulo-egipcio-sodalita-1043',
    name: 'Pêndulo Egípcio – Sodalita',
    category: 'radiestesia',
    subcategory: 'pendulos',
    categoryLabel: 'Pêndulos',
    description: 'Pêndulo Egípcio – Sodalita — peça da linha Radiestesia da Quéops Pirâmides.',
    longDescription: 'Pêndulo Sodalita Ponta Egípcio com Corrente O Pêndulo Sodalita Egípcio é um instrumento de radiestesia utilizado para obter respostas intuitivas e auxiliar no autoconhecimento. Com formato em ponta, proporciona precisão em práticas de análise energética. O Pêndulo de Sodalita é capaz de proporcionar clareza e orientação, canalizando energias para revelar respostas com precisão e profundidade Para utilizá-lo, segure a corrente e concentre-se em sua pergunta. O movimento do pêndulo indicará a resposta desejada, auxiliando no processo de percepção e equilíbrio pessoal. Tamanho: 4 cm Material: Cri',
    price: 48,
    stock: 25,
    image: 'https://queopspiramides.com.br/wp-content/uploads/2025/11/1000428816.png',
    weight: '',
    sku: 'QP-1043',
  },
  {
    id: 'bussola-1044',
    name: 'Bússola',
    category: 'radiestesia',
    subcategory: 'bussolas',
    categoryLabel: 'Bússolas',
    description: 'Bússola com Norte Magnético e Verdadeiro. Medidas – 9cm x 6cm x 2cm Como usar: Para nortear a pirâmide é preciso apontar a ponta da bússola no Norte Magnético, e posicionar a pirâm',
    longDescription: 'Bússola com Norte Magnético e Verdadeiro – Orientação Precisa para Suas Medições Obtenha medições precisas com nossa bússola que indica tanto o norte magnético quanto o verdadeiro. Ideal para orientar pirâmides, esta bússola é uma ferramenta essencial para quem busca precisão. Como usar Aponte a agulha da bússola para o norte magnético Posicione a pirâmide no norte verdadeiro Lembre-se o Norte magnético é para onde aponta a agulha da bússola O norte verdadeiro aponta para o norte geográfico O norte magnético fica ligeiramente deslocado do norte geográfico (verdadeiro) Em São Paulo o desvio mag',
    price: 48,
    stock: 25,
    image: 'https://queopspiramides.com.br/wp-content/uploads/2026/06/1782237609_aee91e86c427d0cfb0c6e2c264d58175.png',
    weight: '',
    sku: 'QP-1044',
  },
  {
    id: 'adesivo-grafico-radiestesia-andre-phillippe-g-6cm-1045',
    name: 'Adesivo Gráfico Radiestesia André Phillippe G – 6cm',
    category: 'radiestesia',
    subcategory: 'radiestesia',
    categoryLabel: 'Radiestesia',
    description: 'Adesivo Gráfico Radiestesia André Phillippe G – 6cm — peça da linha Radiestesia da Quéops Pirâmides.',
    longDescription: 'Gráfico Radiestésico André Philippe (Tamanho G) – Adesivo de Proteção Energética Adesivo radiônico ideal para neutralizar energias nocivas emitidas por aparelhos eletrônicos. Dimensões: 6,5cm x 6cm Indicado para proteção contra irradiações elétricas de televisores, geladeiras, micro-ondas, computadores e outros dispositivos. Deve ser colocado próximo aos equipamentos para equilibrar as influências energéticas no ambiente.',
    price: 2,
    stock: 25,
    image: 'https://queopspiramides.com.br/wp-content/uploads/2026/04/1774482012_f28ad26ef9aa2684b19b82d5268234e3.png',
    weight: '',
    sku: 'QP-1045',
  },
  {
    id: 'cruz-ansata-preta-dourada-resina-veronese-1046',
    name: 'Cruz Ansata Preta Dourada Resina Veronese',
    category: 'religiosos',
    subcategory: 'cruzes',
    categoryLabel: 'Cruzes',
    description: 'Cruz Ansata Preta Dourada Resina Veronese — peça da linha Religiosos da Quéops Pirâmides.',
    longDescription: 'Cruz Ansata Ankh Preta e Dourada em Resina – Veronese Design Collection A Cruz Ansata, também chamada de Ankh ou "Chave da Vida", é um dos símbolos mais icônicos do Egito Antigo, representando proteção, conhecimento, transformação e a conexão entre os mundos material e espiritual. Presente em templos, túmulos e artefatos egípcios, era carregada pelos deuses como um emblema de poder sobre a vida e a eternidade. Esta escultura, produzida pela renomada Veronese Design Collection, é uma peça de altíssima qualidade, com detalhes primorosos e acabamento impecável. A marca Veronese é reconhecida mund',
    price: 845,
    tag: 'DESTAQUE',
    stock: 1,
    image: 'https://queopspiramides.com.br/wp-content/uploads/2026/05/1000632566.png',
    weight: '',
    sku: 'QP-1046',
  },
  {
    id: 'chapa-de-agata-com-gravacao-a-laser-g-ref-rei-106-1047',
    name: 'Chapa de Ágata com Gravação a Laser G – Ref. Rei 106',
    category: 'religiosos',
    subcategory: 'cristo',
    categoryLabel: 'Cristo',
    description: 'Chapa de Ágata com Gravação a Laser G – Ref. Rei 106 — peça da linha Religiosos da Quéops Pirâmides.',
    longDescription: 'Chapa de &Aacute;gata com Grava&ccedil;&atilde;o a Laser G Chapa de &aacute;gata &eacute; uma fatia polida da pedra &aacute;gata, uma variedade de quartzo calced&ocirc;nia conhecida por suas faixas coloridas naturais. Essas pe&ccedil;as s&atilde;o amplamente utilizadas tanto pela est&eacute;tica quanto por propriedades esot&eacute;ricas atribu&iacute;das ao cristal. A grava&ccedil;&atilde;o detalhada a laser ressalta o simbolismo espiritual e transforma o geodo em um objeto de contempla&ccedil;&atilde;o. A &aacute;gata &eacute; reconhecida por suas propriedades energ&eacute;ticas poderosas. El',
    price: 278,
    stock: 25,
    image: 'https://queopspiramides.com.br/wp-content/uploads/2026/05/1774466415_edfecdad457005c4b2a18ab0d20c7ebf.png',
    weight: '',
    sku: 'QP-1047',
  },
  {
    id: 'chapa-de-agata-com-gravacao-a-laser-gg-ref-rei-107-1048',
    name: 'Chapa de Ágata com Gravação a Laser GG – Ref. Rei 107',
    category: 'religiosos',
    subcategory: 'cristo',
    categoryLabel: 'Cristo',
    description: 'Chapa de Ágata com Gravação a Laser GG – Ref. Rei 107 — peça da linha Religiosos da Quéops Pirâmides.',
    longDescription: 'Geodo de &Aacute;gata com Grava&ccedil;&atilde;o a Laser GG Chapa de &aacute;gata &eacute; uma fatia polida da pedra &aacute;gata, uma variedade de quartzo calced&ocirc;nia conhecida por suas faixas coloridas naturais. Essas pe&ccedil;as s&atilde;o amplamente utilizadas tanto pela est&eacute;tica quanto por propriedades esot&eacute;ricas atribu&iacute;das ao cristal. A grava&ccedil;&atilde;o detalhada a laser ressalta o simbolismo espiritual e transforma o geodo em um objeto de contempla&ccedil;&atilde;o. A &aacute;gata &eacute; reconhecida por suas propriedades energ&eacute;ticas poderosas. E',
    price: 950,
    stock: 2,
    image: 'https://queopspiramides.com.br/wp-content/uploads/2026/05/1774467004_96b689a55e846dd9c5f21a3058514b12.png',
    weight: '',
    sku: 'QP-1048',
  },
  {
    id: 'geodo-de-agata-com-gravacao-a-laser-p-ref-rei-108-1049',
    name: 'Geodo de Ágata com Gravação a Laser P – Ref. Rei 108',
    category: 'religiosos',
    subcategory: 'cristo',
    categoryLabel: 'Cristo',
    description: 'Geodo de Ágata com Gravação a Laser P – Ref. Rei 108 — peça da linha Religiosos da Quéops Pirâmides.',
    longDescription: 'Geodo de &Aacute;gata com Grava&ccedil;&atilde;o a Laser P Geodo de &aacute;gata natural com grava&ccedil;&atilde;o a laser de alta qualidade. Cada pe&ccedil;a &eacute; &uacute;nica, com forma e colora&ccedil;&atilde;o pr&oacute;prias, evidenciando a beleza natural da &aacute;gata e o cuidado na confec&ccedil;&atilde;o artesanal. A grava&ccedil;&atilde;o detalhada a laser ressalta o simbolismo espiritual e transforma o geodo em um objeto de contempla&ccedil;&atilde;o. A &aacute;gata &eacute; reconhecida por suas propriedades energ&eacute;ticas poderosas. Ela ajuda a harmonizar o ambiente, fort',
    price: 195,
    stock: 0,
    image: 'https://queopspiramides.com.br/wp-content/uploads/2026/04/1774467006_edfecdad457005c4b2a18ab0d20c7ebf.png',
    weight: '',
    sku: 'QP-1049',
  },
  {
    id: 'cruz-mosaico-g-ref-vil-03-1050',
    name: 'Cruz Mosaico G – Ref. Vil 03',
    category: 'religiosos',
    subcategory: 'cruzes',
    categoryLabel: 'Cruzes',
    description: 'Cruz Mosaico G – Ref. Vil 03 — peça da linha Religiosos da Quéops Pirâmides.',
    longDescription: 'Cruz em Mosaico Cruz em mosaico feita &agrave; m&atilde;o, criada pe&ccedil;a por pe&ccedil;a com dedica&ccedil;&atilde;o artesanal. Seu design colorido e detalhado valoriza qualquer ambiente, trazendo beleza e um toque espiritual &agrave; decora&ccedil;&atilde;o. Cada fragmento de mosaico confere exclusividade, tornando a pe&ccedil;a &uacute;nica e especial. Ideal para paredes, altares e espa&ccedil;os de ora&ccedil;&atilde;o. O que &eacute; Mosaico Cer&acirc;mica? &Eacute; uma obra de arte decorativa formada pela jun&ccedil;&atilde;o de pequenas pe&ccedil;as (tesselas) de cer&acirc;mica colo',
    price: 298,
    stock: 25,
    image: 'https://queopspiramides.com.br/wp-content/uploads/2026/03/1771461605_9717bee23b2f1bcfee28f0296e8ff168.png',
    weight: '',
    sku: 'QP-1050',
  },
  {
    id: 'cruz-mosaico-m-ref-vil-02-1051',
    name: 'Cruz Mosaico M – Ref. Vil 02',
    category: 'religiosos',
    subcategory: 'cruzes',
    categoryLabel: 'Cruzes',
    description: 'Cruz Mosaico M – Ref. Vil 02 — peça da linha Religiosos da Quéops Pirâmides.',
    longDescription: 'Cruz em Mosaico Cruz em mosaico feita &agrave; m&atilde;o, criada pe&ccedil;a por pe&ccedil;a com dedica&ccedil;&atilde;o artesanal. Seu design colorido e detalhado valoriza qualquer ambiente, trazendo beleza e um toque espiritual &agrave; decora&ccedil;&atilde;o. Cada fragmento de mosaico confere exclusividade, tornando a pe&ccedil;a &uacute;nica e especial. Ideal para paredes, altares e espa&ccedil;os de ora&ccedil;&atilde;o. O que &eacute; Mosaico Cer&acirc;mica? &Eacute; uma obra de arte decorativa formada pela jun&ccedil;&atilde;o de pequenas pe&ccedil;as (tesselas) de cer&acirc;mica colo',
    price: 140,
    stock: 25,
    image: 'https://queopspiramides.com.br/wp-content/uploads/2026/04/1774482912_b5c7231283ef90f0b9b057acfb0d98c3.png',
    weight: '',
    sku: 'QP-1051',
  },
  {
    id: 'estatua-sekhmet-deusa-leoa-veronese-1052',
    name: 'Estátua Sekhmet Deusa Leoa Veronese',
    category: 'religiosos',
    subcategory: 'egipcios',
    categoryLabel: 'Egípcios',
    description: 'Estátua Sekhmet Deusa Leoa Veronese — peça da linha Religiosos da Quéops Pirâmides.',
    longDescription: 'Estátua Sekhmet Deusa Leoa em Resina Veronese Sekhmet é a deusa egípcia da Verdade e da Justiça, do poder, do fogo solar, da guerra e da cura. Representada com corpo de mulher e cabeça de leoa, simboliza força, proteção e transformação. Criada pelo deus Rá para restaurar a ordem, ela expressa a dualidade entre destruição e cura: sua fúria podia devastar, mas sua energia também afastava doenças e promovia saúde. Usando o disco solar sobre a cabeça, era vista como guardiã dos faraós e patrona dos médicos. Adorada especialmente em Mênfis, Sekhmet era celebrada com música, incensos e rituais de pu',
    price: 1198,
    stock: 1,
    image: 'https://queopspiramides.com.br/wp-content/uploads/2025/11/1000428768.png',
    weight: '',
    sku: 'QP-1052',
  },
  {
    id: 'estatua-akhenaton-18cm-veronese-1053',
    name: 'Estátua Akhenaton 18cm Veronese',
    category: 'religiosos',
    subcategory: 'egipcios',
    categoryLabel: 'Egípcios',
    description: 'Estátua Akhenaton 18cm Veronese — peça da linha Religiosos da Quéops Pirâmides.',
    longDescription: 'Estátua Akhenaton em Resina Veronese O faraó e companheiro de Nefertiti instaurou o monoteísmo muito antes da cultura cristã. Akhenaton foi responsável por implantar o monoteísmo no Egito Antigo após 1,5 mil anos de adoração a diversas figuras divinas. A medida decidiu estabelecer o deus Aton, figura representada pelo Sol em seu círculo de raios de luz visualizado a olho nu pelo céu, como divindade máxima, proibindo o culto a qualquer outro deus. Akhenaton nasceu no ano de 1372 a.C. e faleceu em 1336 a.C. Foi casado com Nefertiti, que, segundo historiadores, teve grande influência política no ',
    price: 737,
    stock: 1,
    image: 'https://queopspiramides.com.br/wp-content/uploads/2025/11/1000428763.png',
    weight: '',
    sku: 'QP-1053',
  },
  {
    id: 'estatua-gato-deusa-bastet-branca-7cm-1054',
    name: 'Estátua Gato Deusa Bastet Branca 7cm',
    category: 'religiosos',
    subcategory: 'egipcios',
    categoryLabel: 'Egípcios',
    description: 'Estátua Gato Deusa Bastet Branca 7cm — peça da linha Religiosos da Quéops Pirâmides.',
    longDescription: 'Estátua da Deusa Bastet Branca em Resina 7cm Escultura de Bastet em resina, com excelente acabamento. Tamanho: 7cm x 2,5cm x 3cm Material: Resina Características: Excelente acabamento Bastet é a deusa egípcia da verdade, justiça, lar, fertilidade e proteção. Conhecida por suas habilidades como "Olho de Ra", Bastet também representa o prazer sensual e a defesa da casa. Simboliza força, proteção e a energia feminina. Ideal para decoração e energização de ambientes, trazendo equilíbrio e harmonia.',
    price: 35,
    stock: 25,
    image: 'https://queopspiramides.com.br/wp-content/uploads/2026/03/1774484116_684d73ddc3cb347d6058f98166b617bc.png',
    weight: '',
    sku: 'QP-1054',
  },
  {
    id: 'tela-canva-20x30-cristo-complacente-1055',
    name: 'Tela Canva 20x30 Cristo Complacente',
    category: 'decoracao',
    subcategory: 'fotos-e-porta-retratos',
    categoryLabel: 'Fotos e Porta Retratos',
    description: 'Tela Canva 20x30 Cristo Complacente — peça da linha Decoração da Quéops Pirâmides.',
    longDescription: 'Tela em Tamanho 20x30, Impress&atilde;o em Canva de Alta Qualidade Imagem: Cristo Complacente. Tela impressa em alta defini&ccedil;&atilde;o sobre tecido canvas, proporcionando apar&ecirc;ncia de pintura cl&aacute;ssica. O canvas, tecido de algod&atilde;o ou linho, &eacute; resistente e dur&aacute;vel, sem necessidade de vidro. Ideal para decora&ccedil;&atilde;o de espa&ccedil;os contemplativos e de reflex&atilde;o. Dimens&otilde;es: 20cm x 30cm Material: Impress&atilde;o digital em canvas Acabamento: Tela Enrolada para facilidade do envio, sem estrutura de madeira',
    price: 120,
    tag: 'DESTAQUE',
    stock: 25,
    image: 'https://queopspiramides.com.br/wp-content/uploads/2026/05/1779817507_2b71c464cab40192bc2500cdd88ceac2.png',
    weight: '',
    sku: 'QP-1055',
  },
  {
    id: 'tela-canva-30x40-cristo-complacente-1056',
    name: 'Tela Canva 30x40 Cristo Complacente',
    category: 'decoracao',
    subcategory: 'fotos-e-porta-retratos',
    categoryLabel: 'Fotos e Porta Retratos',
    description: 'Tela Canva 30x40 Cristo Complacente — peça da linha Decoração da Quéops Pirâmides.',
    longDescription: 'Tela em Tamanho 30x40, Impress&atilde;o em Canva de Alta Qualidade Imagem: Cristo Complacente. Tela impressa em alta defini&ccedil;&atilde;o sobre tecido canvas, proporcionando apar&ecirc;ncia de pintura cl&aacute;ssica. O canvas, tecido de algod&atilde;o ou linho, &eacute; resistente e dur&aacute;vel, sem necessidade de vidro. Ideal para decora&ccedil;&atilde;o de espa&ccedil;os contemplativos e de reflex&atilde;o. Dimens&otilde;es: 30cm x 40cm Material: Impress&atilde;o digital em canvas Acabamento: Tela Enrolada para facilidade do envio, sem estrutura de madeira',
    price: 185,
    stock: 25,
    image: 'https://queopspiramides.com.br/wp-content/uploads/2026/05/1779817213_2b71c464cab40192bc2500cdd88ceac2.png',
    weight: '',
    sku: 'QP-1056',
  },
  {
    id: 'tela-canva-50x70-cristo-complacente-1057',
    name: 'Tela Canva 50x70 Cristo Complacente',
    category: 'decoracao',
    subcategory: 'fotos-e-porta-retratos',
    categoryLabel: 'Fotos e Porta Retratos',
    description: 'Tela Canva 50x70 Cristo Complacente — peça da linha Decoração da Quéops Pirâmides.',
    longDescription: 'Tela em Tamanho 50x70, Impress&atilde;o em Canva de Alta Qualidade Imagem: Cristo Complacente. Tela impressa em alta defini&ccedil;&atilde;o sobre tecido canvas, proporcionando apar&ecirc;ncia de pintura cl&aacute;ssica. O canvas, tecido de algod&atilde;o ou linho, &eacute; resistente e dur&aacute;vel, sem necessidade de vidro. Ideal para decora&ccedil;&atilde;o de espa&ccedil;os contemplativos e de reflex&atilde;o. Dimens&otilde;es: 50cm x 70cm Material: Impress&atilde;o digital em canvas Acabamento: Tela Enrolada para facilidade do envio, sem estrutura de madeira',
    price: 248,
    stock: 25,
    image: 'https://queopspiramides.com.br/wp-content/uploads/2026/05/1779817210_2b71c464cab40192bc2500cdd88ceac2.png',
    weight: '',
    sku: 'QP-1057',
  },
  {
    id: 'estatua-sao-francisco-17cm-1058',
    name: 'Estátua São Francisco 17cm',
    category: 'decoracao',
    subcategory: 'estatuas-e-enfeites',
    categoryLabel: 'Estátuas e Enfeites',
    description: 'Estátua São Francisco 17cm — peça da linha Decoração da Quéops Pirâmides.',
    longDescription: 'Estátua de São Francisco de Assis em Resina 17 cm Estátua detalhada de São Francisco de Assis, confeccionada em resina plástica com excelente acabamento. Representa o santo protetor dos animais e da natureza, símbolo de humildade e paz. Ideal para ambientes de oração ou decoração de espaços importantes. Tamanho: 17cm de altura x 5cm Material: Resina Acabamento: Excelente acabamento A Estátua de São Francisco de Assis traz uma mensagem de serenidade e proteção para sua casa ou altar.',
    price: 130,
    stock: 10,
    image: 'https://queopspiramides.com.br/wp-content/uploads/2026/05/1000630391.png',
    weight: '',
    sku: 'QP-1058',
  },
  {
    id: 'estatua-sao-francisco-bronze-veronese-1059',
    name: 'Estátua São Francisco Bronze Veronese',
    category: 'decoracao',
    subcategory: 'estatuas-e-enfeites',
    categoryLabel: 'Estátuas e Enfeites',
    description: 'Estátua São Francisco Bronze Veronese — peça da linha Decoração da Quéops Pirâmides.',
    longDescription: 'Estátua de São Francisco de Assis Bronze em Resina Veronese 22cm Escultura de São Francisco de Assis em resina, com acabamento primoroso, detalhado e de alta qualidade. Parte da coleção Veronese Design, é uma verdadeira obra de arte, ideal para ambientes religiosos e espaços de reflexão. Tamanho: 22cm de altura x 11cm x 6cm Material: Resina Acabamento: Excelente A resina utilizada pela Veronese Design é de alta resistência e durabilidade, combinando arte, história e cultura. Produzidas com técnicas de bronze fundido a frio, suas peças têm grande riqueza de detalhes, sendo perfeitas para decora',
    price: 818,
    stock: 25,
    image: 'https://queopspiramides.com.br/wp-content/uploads/2026/05/1000630949.png',
    weight: '',
    sku: 'QP-1059',
  },
  {
    id: 'chapa-de-agata-com-gravacao-a-laser-m-ref-rei-105-1060',
    name: 'Chapa de Ágata com Gravação a Laser M – Ref. Rei 105',
    category: 'decoracao',
    subcategory: 'estatuas-e-enfeites',
    categoryLabel: 'Estátuas e Enfeites',
    description: 'Chapa de Ágata com Gravação a Laser M – Ref. Rei 105 — peça da linha Decoração da Quéops Pirâmides.',
    longDescription: 'Chapa de &Aacute;gata com Grava&ccedil;&atilde;o a Laser M Chapa de &aacute;gata &eacute; uma fatia polida da pedra &aacute;gata, uma variedade de quartzo calced&ocirc;nia conhecida por suas faixas coloridas naturais. Essas pe&ccedil;as s&atilde;o amplamente utilizadas tanto pela est&eacute;tica quanto por propriedades esot&eacute;ricas atribu&iacute;das ao cristal. A grava&ccedil;&atilde;o detalhada a laser ressalta o simbolismo espiritual e transforma o geodo em um objeto de contempla&ccedil;&atilde;o. A &aacute;gata &eacute; reconhecida por suas propriedades energ&eacute;ticas poderosas. El',
    price: 238,
    stock: 25,
    image: 'https://queopspiramides.com.br/wp-content/uploads/2026/04/1774466413_96b689a55e846dd9c5f21a3058514b12.png',
    weight: '',
    sku: 'QP-1060',
  },
  {
    id: 'quadro-cristo-sobre-as-aguas-espatulado-p-31x23-ref-grace-51-1061',
    name: 'Quadro Cristo Sobre as Águas Espatulado P 31x23 – Ref. Grace 51',
    category: 'decoracao',
    subcategory: 'quadros',
    categoryLabel: 'Quadros',
    description: 'Quadro Cristo Sobre as Águas Espatulado P 31x23 – Ref. Grace 51 — peça da linha Decoração da Quéops Pirâmides.',
    longDescription: 'Quadro Cristo Sobre as Águas Espatulado 31cm x 23cm Quadro impresso em alta definição sobre tecido canvas, proporcionando aparência de pintura clássica. O canvas, tecido de algodão ou linho, é resistente e durável. Ideal para decoração de espaços contemplativos e de reflexão, sem necessidade de moldura ou vidro. Dimensões: 31cm x 23cm Material: Impressão digital em canvas Acabamento: Estruturado sobre madeira Ref. Grace 51',
    price: 160,
    stock: 0,
    image: 'https://queopspiramides.com.br/wp-content/uploads/2026/07/1778093113_bc56b377ecb7c3c1d3cc417a2ada7dc4.png',
    weight: '',
    sku: 'QP-1061',
  },
  {
    id: 'corrente-de-aco-banho-ouro-50cm-1062',
    name: 'Corrente de Aço Banho Ouro – 50cm',
    category: 'decoracao',
    subcategory: 'pecas-em-aco-inox',
    categoryLabel: 'Peças em Aço Inox',
    description: 'Corrente de Aço Banho Ouro – 50cm — peça da linha Decoração da Quéops Pirâmides.',
    longDescription: 'Corrente em Aço Inoxidável Antialérgica com Banho de Ouro 50cm – Elegância e Durabilidade em um Só Acessório Adicione um toque de sofisticação ao seu visual com nossa corrente em aço inoxidável antialérgica com banho de ouro. Resistente à corrosão e com brilho duradouro, é ideal para uso diário e para quem busca acessórios de alta qualidade e beleza. Como usar Utilize diariamente, de forma segura Indicado para pessoas com alergia a níquel e outros materiais Combine com pingentes e outros acessórios para um visual elegante Especificações Material: Aço inoxidável antialérgico com banho de ouro C',
    price: 90,
    stock: 25,
    image: 'https://queopspiramides.com.br/wp-content/uploads/2026/04/1774482009_2b9e1dea8a7265540e5c1ba3f5814fe8.png',
    weight: '',
    sku: 'QP-1062',
  },
  {
    id: 'quadro-oracao-de-sao-francisco-com-moldura-p-1063',
    name: 'Quadro Oração de São Francisco com Moldura P',
    category: 'decoracao',
    subcategory: 'quadros',
    categoryLabel: 'Quadros',
    description: 'Quadro Oração de São Francisco com Moldura P — peça da linha Decoração da Quéops Pirâmides.',
    longDescription: 'Quadro Oração de São Francisco com Moldura Clássica Dourada P Quadro com moldura clássica dourada, perfeito para agregar elegância e serenidade ao seu espaço. A imagem da oração de São Fracisco é impressa com verniz texturizado, garantindo proteção e durabilidade, sem desbotar com o tempo. Ideal para criar um ambiente acolhedor e harmonioso. Tamanho do quadro com moldura: 0,30 x 0,37 cm Tamanho da imagem: 0,20 x 0,24 cm Imagem: Oração de São Francisco de Assis Imagem protegida com verniz texturizado, garantindo maior resistência e preservação ao longo do tempo.',
    price: 150,
    stock: 2,
    image: 'https://queopspiramides.com.br/wp-content/uploads/2025/09/1000348377.png',
    weight: '',
    sku: 'QP-1063',
  },
  {
    id: 'livro-o-rei-porquinho-e-a-ilha-do-abacaxi-autora-carla-finati-1064',
    name: 'Livro O Rei Porquinho e a Ilha do Abacaxi – Autora Carla Finati',
    category: 'livros-e-midia',
    subcategory: 'infantil',
    categoryLabel: 'Infantil',
    description: 'Livro O Rei Porquinho e a Ilha do Abacaxi – Autora Carla Finati — peça da linha Livros e Mídia da Quéops Pirâmides.',
    longDescription: 'Livro O Rei Porquinho e a Ilha do Abacaxi Sinopse: Numa ilha repleta de frutas, vegetais e alegria, vive o Rei Porquinho, um guloso apaixonado por refeições. Cada dia da semana é uma festa de sabores, com pratos criativos preparados pelos animais da ilha. Mas quando o tédio gastronômico ameaça a todos, o Rei Porquinho tem uma ideia brilhante: um festival onde cada animal cria um prato novo para a Grande Festa de Primavera. O que parecia uma solução deliciosa vira uma aventura hilária, com pratos exóticos que fazem o rei crescer línguas gigantes, bolhas azuis, cabeças de balão e até espinhos de',
    price: 55,
    tag: 'DESTAQUE',
    stock: 25,
    image: 'https://queopspiramides.com.br/wp-content/uploads/2026/07/1778793317_53c0a1e86eee6a93393118aa394ae51f.png',
    weight: '',
    sku: 'QP-1064',
  },
  {
    id: 'livro-o-icone-bizantino-autora-maria-alice-1065',
    name: 'Livro O Ícone Bizantino – Autora Maria Alice',
    category: 'livros-e-midia',
    subcategory: 'livros',
    categoryLabel: 'Livros',
    description: 'Livro O Ícone Bizantino – Autora Maria Alice — peça da linha Livros e Mídia da Quéops Pirâmides.',
    longDescription: 'Livro O Ícone Bizantino – Uma das manifestações divinas – Lançando pontes para o sagrado – Maria Alice',
    price: 70,
    stock: 2,
    image: 'https://queopspiramides.com.br/wp-content/uploads/2026/06/1778793313_4499e7cfc8ecacab177cfb29d245249a.png',
    weight: '',
    sku: 'QP-1065',
  },
  {
    id: 'dvd-silvio-brito-1066',
    name: 'DVD Silvio Brito',
    category: 'livros-e-midia',
    subcategory: 'filmes-dvd-s',
    categoryLabel: 'Filmes DvD\'s',
    description: 'DVD Silvio Brito — peça da linha Livros e Mídia da Quéops Pirâmides.',
    longDescription: 'DVD Silvio Brito 41 Anos Entre Amigos Um registro inesquecível de uma noite mágica! Gravado ao vivo em 21 de junho de 2015, o show "Silvio Brito – Entre Amigos" entrou para a história com casa lotada e uma atmosfera emocionante. Com sua presença marcante e carisma inconfundível, Silvio Brito encantou o público em uma apresentação especial, acompanhado de grandes amigos e talentos da música. Participações emocionantes de Rogério Tutti, Jether Garotti, Paula Psillakis, Irina Bezzan, Rogério Leite, maestro José Paulo Soares, Rodrigo Morandi, além de Marysol e Clarissa, filhas do cantor mineiro, t',
    price: 25,
    stock: 25,
    image: 'https://queopspiramides.com.br/wp-content/uploads/2025/09/1758708013_0e15cd2976fe08d2db4a349c73fd431c.png',
    weight: '',
    sku: 'QP-1066',
  },
  {
    id: 'livro-biblia-sagrada-ave-maria-1067',
    name: 'Livro Bíblia Sagrada Ave Maria',
    category: 'livros-e-midia',
    subcategory: 'livros',
    categoryLabel: 'Livros',
    description: 'Livro Bíblia Sagrada Ave Maria — peça da linha Livros e Mídia da Quéops Pirâmides.',
    longDescription: 'B&iacute;blia Sagrada Ave-Maria com Z&iacute;per &ndash; Edi&ccedil;&atilde;o Completa A B&iacute;blia Sagrada Ave-Maria com z&iacute;per &eacute; uma das edi&ccedil;&otilde;es mais tradicionais e queridas entre os brasileiros. Traduzida diretamente dos textos originais em hebraico, grego e aramaico pelos monges beneditinos de Maredsous, na B&eacute;lgica, esta obra foi publicada pela primeira vez em 1959 pelos mission&aacute;rios do Imaculado Cora&ccedil;&atilde;o de Maria, sendo a primeira B&iacute;blia cat&oacute;lica lan&ccedil;ada no Brasil. Com acabamento em imita&ccedil;&atilde;o de cou',
    price: 249,
    stock: 1,
    image: 'https://queopspiramides.com.br/wp-content/uploads/2026/03/1774488007_585e885b163ea0444ac0da7e18944249.png',
    weight: '',
    sku: 'QP-1067',
  },
  {
    id: 'livro-o-grande-amigo-de-deus-1068',
    name: 'Livro O Grande Amigo de Deus',
    category: 'livros-e-midia',
    subcategory: 'livros',
    categoryLabel: 'Livros',
    description: 'Livro O Grande Amigo de Deus — peça da linha Livros e Mídia da Quéops Pirâmides.',
    longDescription: 'Livro O grande amigo de Deus, de Taylor Caldwell Sinopse Nova edição de um clássico de Taylor Caldwell que retrata a vida de São Paulo. Taylor Caldwell dedicou anos de estudo intenso para escrever O grande amigo de Deus, um romance sobre um dos mais apaixonados, inteligentes e dedicados apóstolos do cristianismo primitivo, Saul de Tarshish, ou, como os romanos o chamavam, Paulo de Tarso, o intelectual, advogado e teólogo fariseu, conhecido como Apóstolo dos Gentios. Paulo exerceu mais influência no mundo ocidental e na cristandade do que a maioria de nós conhece, pois o cristianismo, que ele d',
    price: 290,
    stock: 2,
    image: 'https://queopspiramides.com.br/wp-content/uploads/2025/09/1758717910_e1f907bcf05e84caca036cdbeb16573b.png',
    weight: '',
    sku: 'QP-1068',
  },
  {
    id: 'livro-colecao-o-mundo-sim-autora-veridiana-1069',
    name: 'Livro Coleção O Mundo Sim – Autora Veridiana',
    category: 'livros-e-midia',
    subcategory: 'infantil',
    categoryLabel: 'Infantil',
    description: 'Livro Coleção O Mundo Sim – Autora Veridiana — peça da linha Livros e Mídia da Quéops Pirâmides.',
    longDescription: 'Coleção O Mundo SIM – Autoconhecimento para Adultos e Crianças Desvende os mistérios da mente humana com a coleção O Mundo SIM, uma jornada transformadora de autoconhecimento para adultos e crianças. Composta por três livros, essa coleção promove aprendizado compartilhado e fortalece os laços familiares por meio da leitura e da imaginação. O livro para adultos explora o Consciente, Pré-Consciente e Inconsciente, oferecendo reflexões sobre como nossos pensamentos e emoções moldam comportamentos. Já o livro infantil, "A Casa Mágica", apresenta uma narrativa lúdica onde um menino corajoso enfrent',
    price: 110,
    stock: 25,
    image: 'https://queopspiramides.com.br/wp-content/uploads/2026/05/1778793008_955d65498be59188d447d0751994584b.png',
    weight: '',
    sku: 'QP-1069',
  },
  {
    id: 'pulseira-ambar-infantil-1070',
    name: 'Pulseira Âmbar Infantil',
    category: 'livros-e-midia',
    subcategory: 'infantil',
    categoryLabel: 'Infantil',
    description: 'Pulseira Âmbar Infantil — peça da linha Livros e Mídia da Quéops Pirâmides.',
    longDescription: 'Pulseira de Âmbar Infantil 14cm Pulseira de âmbar báltico, ideal para o contato direto com a pele, liberando substâncias terapêuticas que ajudam na redução da ansiedade, alívio do estresse, melhoria do sono e alívio de dores. Feita com a mais pura resina fóssil de âmbar báltico, importada diretamente da Lituânia, região do mar Báltico. Dimensões: 14cm Material: Âmbar Báltico Garantia de autenticidade e propriedades terapêuticas naturais.',
    price: 178,
    stock: 25,
    image: 'https://queopspiramides.com.br/wp-content/uploads/2026/05/1774498207_31a2031f269811a74b4e6fb2276c1692.png',
    weight: '',
    sku: 'QP-1070',
  },
  {
    id: 'dvd-filme-bakita-a-santa-1071',
    name: 'DVD Filme Bakita A Santa',
    category: 'livros-e-midia',
    subcategory: 'filmes-dvd-s',
    categoryLabel: 'Filmes DvD\'s',
    description: 'DVD Filme Bakita A Santa — peça da linha Livros e Mídia da Quéops Pirâmides.',
    longDescription: 'DVD Filme Bakhita – A Santa (2009) Drama biográfico sobre Santa Josefina Bakhita, a primeira santa africana. Capturada ainda criança no Sudão e forçada à escravidão, Bakhita enfrentou abusos e preconceito até conquistar sua liberdade na Itália. Inspirada pela fé católica, tornou-se religiosa na Ordem das Irmãs Canossianas. Especificações: Gênero: Drama biográfico Ano: 2009 Direção: Giacomo Campiotti Elenco: Fabio Sartor, Stefania Rocca, Sonia Bergamasco Idioma: Italiano (legendado) Formato: DVD Uma história emocionante de fé, superação e amor ao próximo.',
    price: 55,
    stock: 25,
    image: 'https://queopspiramides.com.br/wp-content/uploads/2025/09/1758730510_c7da79a5cae67672a3fb6f89866f84bf.png',
    weight: '',
    sku: 'QP-1071',
  },
  {
    id: 'dvd-filme-dr-moscati-1072',
    name: 'DVD Filme Dr. Moscati',
    category: 'livros-e-midia',
    subcategory: 'filmes-dvd-s',
    categoryLabel: 'Filmes DvD\'s',
    description: 'DVD Filme Dr. Moscati — peça da linha Livros e Mídia da Quéops Pirâmides.',
    longDescription: 'DVD Filme Dr. Moscati – O Doutor Que Virou Santo (2007) Drama biográfico sobre Giuseppe Moscati, médico italiano que dedicou sua vida ao cuidado dos pobres no final do século XIX e início do século XX. Destacou-se no combate à cólera, no resgate de vítimas da erupção do Vesúvio e na pesquisa que levou à descoberta da insulina. Um dos poucos leigos canonizados pela Igreja Católica. Especificações: Gênero: Drama biográfico Ano: 2007 Duração: Parte 1 – 102 min | Parte 2 – 98 min Direção: Giacomo Campiotti Elenco: Beppe Fiorello, Kasia Smutniak, Ettore Bassi Idioma: Italiano (legendado) Formato: D',
    price: 96,
    stock: 25,
    image: 'https://queopspiramides.com.br/wp-content/uploads/2025/09/1758730512_ee850bf27e3b6bc02d908a542ee5ef4a.png',
    weight: '',
    sku: 'QP-1072',
  },
];
